### ISSUE TITLE
Please clarify with which variant of the QAZ PCB this case is compatible

### ISSUE THREAD

**Issue by xtaran** [dingusxmcgee/QAZ-Simple#1]
[cbk currently sells the QAZ PCB only](https://www.cbkbd.com/product/qaz-keyboard-kit) but in two variants, one with an onboard MCU and one for use with a Pro Micro. Given that the Pro Micro is usually bottom-mounted on such PCBs, the Micro-USB port will be at a slight lower level than with an onboard MCU and onboard MicroUSB socket.

So I wonder if the case is compatible with both variants of the PCB or just one of them. In the letter case: With which?

**Comment by Alasofia** [comment]
This case is compatible with both the integrated and pro micro versions. The USB ports are positioned almost identically. They're not precisely the same, but it's a very very minute difference.

**Comment by dingusxmcgee** [comment]
Alas answered this sufficiently, closing issue :)
